#config_version=6

#config_version=6

videos:
  base_idle_loop:
    file: skillshot/skillshot_ball_in_plunger_lane.ogv
    
  ball_launch_video:
    file: skillshot/skillshot_ball_launched.ogv
    
  # Skillshot videos (add as many as you have)
  skillshot_video_1:
    file: skillshot/skillshot_hit_enhanced.ogv
    
  skillshot_video_2:
    file: skillshot/skillshot_hit_epic.ogv

  skillshot_video_3:
    file: skillshot/skillshot_hit_standard.ogv

  skillshot_video_4:
    file: skillshot/skillshot_hit_super.ogv

event_player:
  # Debug events to track what's happening
 # mode_base_started: video_idle_start
  balldevice_bd_plunger_ejecting_ball: video_idle_start
  s_shooter_lane_inactive: video_launch_start